### ISSUE TITLE
unable to resolve host address ‘glaros.dtc.umn.edu’

### ISSUE THREAD

**Issue by ghost** [coin-or-tools/ThirdParty-Metis#1]
Recently, I used this repo to download Metis, and I found that the script **get.Metis** didn't work.
Since resolving `glaros.dtc.umn.edu` failed.

> Running script for downloading the source code for the METIS
>
> Downloading the source code from glaros.dtc.umn.edu...
> --2019-11-08 15:12:21--  http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/OLD/metis-4.0.3.tar.gz
> Resolving glaros.dtc.umn.edu (glaros.dtc.umn.edu)... failed: Name or service not known.
> wget: unable to resolve host address ‘glaros.dtc.umn.edu’

I guess maybe the Prof. has leaved the school and then the homepage is lost.

Is there any way to download Metis?

**Comment by svigerske** [comment]
Seems that their server is back online.
```
$ ./get.Metis 
 
Running script for downloading the source code for the METIS
 
Downloading the source code from glaros.dtc.umn.edu...
--2019-11-12 05:36:48--  http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/OLD/metis-4.0.3.tar.gz
Resolving glaros.dtc.umn.edu (glaros.dtc.umn.edu)... 160.94.40.33
Connecting to glaros.dtc.umn.edu (glaros.dtc.umn.edu)|160.94.40.33|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 522624 (510K) [application/x-gzip]
Saving to: ‘metis-4.0.3.tar.gz’

metis-4.0.3.tar.gz                     100%[============================================================================>] 510.38K   198KB/s    in 2.6s    

2019-11-12 05:36:52 (198 KB/s) - ‘metis-4.0.3.tar.gz’ saved [522624/522624]

Uncompressing the tarball...
Unpacking the source code...
Applying a patch...
patching file metis-4.0.3/Lib/ccgraph.c
Renaming directory to match source code name...
Deleting the tar file...
 
Done downloading the source code for METIS.
```

**Comment by ghost** [comment]
Yeah! It's ok now!

> $ ./get.Metis 
>
> Running script for downloading the source code for the METIS
>
> Downloading the source code from glaros.dtc.umn.edu...
> --2019-11-12 12:41:15--  http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/OLD/metis-4.0.3.tar.gz
> Resolving glaros.dtc.umn.edu (glaros.dtc.umn.edu)... 160.94.40.33
> Connecting to glaros.dtc.umn.edu (glaros.dtc.umn.edu)|160.94.40.33|:80... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 522624 (510K) [application/x-gzip]
> Saving to: ‘metis-4.0.3.tar.gz’
>
> metis-4.0.3.tar.gz   44%[=======>            ] 228.44K  15.9KB/s    eta metis-4.0.3.tar.g 100%[=============>] 510.38K  10.6KB/s    in 48s     
>
> 2019-11-12 12:42:04 (10.5 KB/s) - ‘metis-4.0.3.tar.gz’ saved [522624/522624]
>
> Uncompressing the tarball...
> Unpacking the source code...
> Applying a patch...
> patching file metis-4.0.3/Lib/ccgraph.c
> Renaming directory to match source code name...
> Deleting the tar file...
>
> Done downloading the source code for METIS.

**Comment by tkralphs** [comment]
@svigerske Should we create a backup download location, as we have for other projects in case this happens again?

**Comment by tkralphs** [comment]
Seems not to be working again...

**Comment by svigerske** [comment]
> @svigerske Should we create a backup download location, as we have for other projects in case this happens again?

Yes. I've set this up and put into trunk, stable/1.3, and stable/2.0. Should I make releases?

**Comment by tkralphs** [comment]
I guess it would be nice to make the original authors site the primary, but I do understand why you didn't do that, given the issues. I'll leave it to you to decide and then sure, make releases. By the way, Mumps and Glpk downloads are also failing pretty regularly. Let's do those, too.

**Comment by phunghoabk** [comment]
It happened again, I cannot download it. Anyone can help me.

**Comment by svigerske** [comment]
You can download from https://github.com/coin-or-tools/ThirdParty-Metis/tree/gh-pages

**Comment by tkralphs** [comment]
https://coin-or.github.io/coin-or-tools/ThirdParty-Metis/metis-4.0.3.tar.gz should already be the default download location unless you are using an old version (<= 1.2).
