### ISSUE TITLE
Implicit declaration of function __GKfree

### ISSUE THREAD

**Issue by Filippo-Tamagnini** [coin-or-tools/ThirdParty-Metis#3]
Running `make` after configuration i got the following error in Ubuntu 24.10:

```
QWERTY@ASDFG:~/Ipopt/ThirdParty-Metis$ make
  CC       metis-4.0/Lib/compress.lo
In file included from ./metis-4.0/Lib/metis.h:35,
                 from metis-4.0/Lib/compress.c:15:
metis-4.0/Lib/compress.c: In function '__CompressGraph':
./metis-4.0/Lib/rename.h:380:41: error: implicit declaration of function '__GKfree'; did you mean 'GKfree'? [-Wimplicit-function-declaration]
  380 | #define GKfree                          __GKfree
      |                                         ^~~~~~~~
metis-4.0/Lib/compress.c:151:3: note: in expansion of macro 'GKfree'
  151 |   GKfree(&keys, &map, &mark, LTERM);
      |   ^~~~~~
make: *** [Makefile:761: metis-4.0/Lib/compress.lo] Errore 1
```

I worked around the issue by adding the tag -fpermissive to CFLAGS in the makefile before compiling. 

I understood that the compiler complains about __GKfree being called before declaration at some point in the C code (this behavior was silently passed as a warning with previous compiler versions). The -fpermissive tag restores the previous compilation behavior and is described in this document: https://gcc.gnu.org/onlinedocs/gcc-14.2.0/gcc/Warning-Options.html#index-Wimplicit-function-declaration and also here https://public-inbox.gentoo.org/gentoo-dev/?x=t&q=xarchiveshash:dd9f2d3082b8b6f8dfbccb0639e6e240 for a different system

**Comment by arrowd** [comment]
I'd argue that a correct fix would be to actually rename the declaration to match the name at the callsite.

Note that this fix does not work for Clang/Flang - instead it needs the `-Wno-implicit-function-declaration` flag.

**Comment by tkralphs** [comment]
We don't maintain METIS, we just provide a wrapper script to download it easily and a build harness. So there are limited options for dealing with this. If someone reports the problem upstream and there is a new release that fixes the issue, then we could incorporate that.
